### PR TITLE
fix: enabling debug should be done before starting up the agent

### LINKED ISSUE #6: Implement LUMIGO_DEBUG support
If the `LUMIGO_DEBUG` env var is set to `true`, set the default value for logging to `debug`.

### PR DESCRIPTION
**Pull request by AlmogBaku**
This change fixes the `LUMIGO_DEBUG` flag by setting it in the `premain`.

closes #6

### CODE REVIEW

File: custom/src/main/java/io/lumigo/javaagent/LumigoConfigurator.java [hunk 1]
```diff
@@ -83,8 +82,12 @@ private Map<String, String> propertiesCustomizer(ConfigProperties cfg) {
     if (accessToken == null || accessToken.isEmpty()) {
       logger.warning("Lumigo Tracer Token is not set. Tracing is disabled.");
     } else {
-      String rawHeaders = cfg.getString("otel.exporter.otlp.headers", "");
-      List<String> headers = new ArrayList<>(Arrays.asList(rawHeaders.split(",")));
+      List<String> headers = new ArrayList<>();
+
+      String rawHeaders = cfg.getString("otel.exporter.otlp.headers");
+      if (rawHeaders != null) {
+        headers = new ArrayList<>(Arrays.asList(rawHeaders.split(",")));
```
Comment (mmanciop) [inline custom/src/main/java/io/lumigo/javaagent/LumigoConfigurator.java:89]: This should be an `addAll` to the list on line #85

**Comment by AlmogBaku** [comment]
done. see readme changes via #12

**Review by mmanciop — APPROVED** [review]
