### PR TITLE
fix: disable ec2 resource provider

### LINKED ISSUE #25: Disable EC2 Resoure
@mmanciop :
The Ec2 resource provider spews a LOT of spurious logs if not running on Ec2. I don't want it on.

A build step that modifies the file in META-INF it before packaging should do it

### PR DESCRIPTION
**Pull request by AlmogBaku**
fixes #25

### CODE REVIEW

File: smoke-tests/src/test/java/io/lumigo/javaagent/smoketest/SpringBootSmokeTest.java [hunk 1]
```diff
@@ -29,6 +33,20 @@
...
 
 class SpringBootSmokeTest extends SmokeTest {
+  @Test
+  public void testResourceProviders() throws IOException {
+    URL url =
+        new URL(
+            "jar:file:"
+                + agentPath
+                + "!/inst/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider");
+    InputStream is = url.openStream();
```
Comment (mmanciop) [inline smoke-tests/src/test/java/io/lumigo/javaagent/smoketest/SpringBootSmokeTest.java:43]: The lack of try-with-resource usage is going to make the code analyzer weep, please fix it ;-)

**Review by mmanciop — CHANGES_REQUESTED** [review]

File: smoke-tests/src/test/java/io/lumigo/javaagent/smoketest/SpringBootSmokeTest.java (hunk 1 above)
Comment (AlmogBaku) [reply smoke-tests/src/test/java/io/lumigo/javaagent/smoketest/SpringBootSmokeTest.java:43]: The whole method can return an IOException (which will fail the test), we don't need try-catch...

**Comment by AlmogBaku** [comment]
Rewrite to use https://hamcrest.org/JavaHamcrest/

**Review by mmanciop — APPROVED** [review]
